server:
  port: ${SERVER_PORT}

spring:
  application:
    name: Hexagonal-Architecture-Learning
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

logging:
  level:
    cosso.com.example.hexagonal_architecture: debug

